import type { Metadata } from "next";
import { Open_Sans, Bitter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/providers";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-open-sans",
});
const bitter = Bitter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-bitter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${opensans.variable} ${bitter.variable} font-sans antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
